select name from constructors order by name;
select name from constructors where nationality in ('Italian');
select name from constructors where name like '%Racing%';
select name from constructors where constructorRef is not null;
select nationality, COUNT(*) as cantidad_constructores from constructors group by nationality order by cantidad_constructores desc;
select name from constructors where name like 'A%';
select name from constructors where constructorRef like '%team';
select name from constructors where name like '% %';
select name, nationality from constructors where nationality in ('British', 'German');
select upper(name) as NOMBRE from constructors;
select name, constructorRef from constructors where replace(name, ' ', '') = constructorRef ;
SELECT name, LENGTH(name) AS cantidad_caracteres FROM constructors WHERE LENGTH(name) > 10;
select name, nationality from constructors where nationality like'F%';
select name from constructors where name like '%x%';
select name, constructorRef from constructors order by constructorRef;
select name from constructors where name like'%GP';
select name, nationality from constructors where nationality != 'British';
select name from constructors where name like '%-%';
select lower(constructorRef) as referencia_constructores, constructorRef from constructors;
select name, constructorRef from constructors where name = constructorRef;
select name from constructors where name regexp '[0-9]';
select name from constructors where name like '%Team%';
select name, nationality from constructors where nationality in ('French');
select nationality, count(*) as cantidad_constructores from constructors group by nationality order by cantidad_constructores;
select lower(name) as nombre from constructors;