select forename, surname, dob from drivers order by dob;
select forename, surname, number from drivers where number is not null;
select forename, surname from drivers where code= concat(LEFT(forename,1), left(surname,1) );
select nationality, count(*) as num_pilotos from drivers group by nationality;
select forename, surname from drivers where dob>= '2000-01-01';
select forename, surname from drivers where forename like '%Alex%';
select forename, surname from drivers where code is null;
select forename, surname from drivers where forename=surname;
select forename, surname from drivers where month(dob)='12';
select surname from drivers where length (surname)>10;
select forename from drivers where forename like '%-%';
select forename from drivers where forename like '% %';
select forename, surname from drivers where left(forename,1)= right(forename,1);
select forename, surname, dob from drivers where day (dob)='1';
select forename, surname, code from drivers where length(code)=3;
select forename, surname from drivers where number>50;
select forename, url from drivers where url is not null;
select forename, driverRef from drivers where driverRef like '%senna%';
select floor(year(dob)/10)*10 as decada, count(*) as total from drivers group by decada order by decada;
select forename, surname from drivers where length(forename)= 4;
select forename, surname from drivers where surname regexp '(.)\\1';
select forename from drivers where code=driverRef;
select forename, surname, number from drivers where number between 10 and 20;
select forename from drivers where forename like '%x%';
select forename from drivers order by length(forename) desc;